CREATE TABLE IF NOT EXISTS settings (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    key TEXT NOT NULL UNIQUE,
    value TEXT NOT NULL
);

CREATE TABLE IF NOT EXISTS tls (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    name TEXT NOT NULL,
    server TEXT NOT NULL DEFAULT '{}',
    client TEXT NOT NULL DEFAULT '{}'
);

CREATE TABLE IF NOT EXISTS users (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    username TEXT NOT NULL UNIQUE,
    password TEXT NOT NULL,
    last_logins TEXT NOT NULL DEFAULT ''
);

CREATE TABLE IF NOT EXISTS user_sessions (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    session_id TEXT NOT NULL UNIQUE,
    user_id INTEGER NOT NULL,
    expires_at INTEGER NOT NULL,
    created_at INTEGER NOT NULL,
    FOREIGN KEY (user_id) REFERENCES users (id) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS tokens (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    desc TEXT NOT NULL DEFAULT '',
    token TEXT NOT NULL UNIQUE,
    expiry INTEGER NOT NULL DEFAULT 0,
    user_id INTEGER NOT NULL,
    FOREIGN KEY (user_id) REFERENCES users (id) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS outbounds (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    kind TEXT NOT NULL,
    tag TEXT NOT NULL UNIQUE,
    options TEXT NOT NULL DEFAULT '{}'
);

CREATE TABLE IF NOT EXISTS inbounds (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    kind TEXT NOT NULL,
    tag TEXT NOT NULL UNIQUE,
    allow_lan_access INTEGER NOT NULL DEFAULT 0,
    tls_id INTEGER DEFAULT NULL,
    addrs TEXT NOT NULL DEFAULT '[]',
    out_json TEXT NOT NULL DEFAULT '{}',
    options TEXT NOT NULL DEFAULT '{}',
    FOREIGN KEY (tls_id) REFERENCES tls (id) ON DELETE RESTRICT
);

CREATE TABLE IF NOT EXISTS services (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    kind TEXT NOT NULL,
    tag TEXT NOT NULL UNIQUE,
    tls_id INTEGER DEFAULT NULL,
    options TEXT NOT NULL DEFAULT '{}',
    FOREIGN KEY (tls_id) REFERENCES tls (id) ON DELETE RESTRICT
);

CREATE TABLE IF NOT EXISTS endpoints (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    kind TEXT NOT NULL,
    tag TEXT NOT NULL UNIQUE,
    options TEXT NOT NULL DEFAULT '{}',
    ext TEXT NOT NULL DEFAULT '{}'
);

CREATE TABLE IF NOT EXISTS clients (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    enable INTEGER NOT NULL DEFAULT 1,
    name TEXT NOT NULL UNIQUE,
    config TEXT NOT NULL DEFAULT '{}',
    inbounds TEXT NOT NULL DEFAULT '[]',
    links TEXT NOT NULL DEFAULT '[]',
    volume INTEGER NOT NULL DEFAULT 0,
    expiry INTEGER NOT NULL DEFAULT 0,
    down INTEGER NOT NULL DEFAULT 0,
    up INTEGER NOT NULL DEFAULT 0,
    desc TEXT NOT NULL DEFAULT '',
    group_name TEXT NOT NULL DEFAULT '',
    delay_start INTEGER NOT NULL DEFAULT 0,
    auto_reset INTEGER NOT NULL DEFAULT 0,
    reset_days INTEGER NOT NULL DEFAULT 0,
    next_reset INTEGER NOT NULL DEFAULT 0,
    total_up INTEGER NOT NULL DEFAULT 0,
    total_down INTEGER NOT NULL DEFAULT 0
);

CREATE TABLE IF NOT EXISTS stats (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    date_time INTEGER NOT NULL,
    resource TEXT NOT NULL,
    tag TEXT NOT NULL,
    direction INTEGER NOT NULL,
    traffic INTEGER NOT NULL
);

CREATE TABLE IF NOT EXISTS changes (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    date_time INTEGER NOT NULL,
    actor TEXT NOT NULL,
    key TEXT NOT NULL,
    action TEXT NOT NULL,
    obj TEXT NOT NULL DEFAULT '{}'
);

CREATE INDEX IF NOT EXISTS idx_stats_resource_tag_time ON stats(resource, tag, date_time);
CREATE INDEX IF NOT EXISTS idx_changes_datetime ON changes(date_time);
