---
services:
  s-ui:
    image: ghcr.io/ytjungle666/yt-home-rust:latest
    container_name: yt-home
    hostname: "yt-home"
    volumes:
      - "./db:/app/db"
      - "./cert:/app/cert"
    tty: true
    restart: unless-stopped
    ports:
      - "80:80"
      - "2096:2096"
    networks:
      - s-ui

networks:
  s-ui:
    driver: bridge
