name: CI

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  validate:
    runs-on: ubuntu-latest
    env:
      NODE_VERSION: "25"
    steps:
      - name: Checkout repository
        uses: actions/checkout@v6.0.2

      - name: Setup Node.js
        uses: actions/setup-node@v6
        with:
          node-version: ${{ env.NODE_VERSION }}
          cache: npm
          cache-dependency-path: frontend/package-lock.json

      - name: Build frontend
        run: |
          cd frontend
          npm ci
          npm run build
          cd ..
          mkdir -p web/html
          rm -rf web/html/*
          cp -R frontend/dist/. web/html/

      - name: Setup Go
        uses: actions/setup-go@v6
        with:
          cache: false
          go-version-file: go.mod

      - name: Run unit tests
        run: go test ./service/... ./sub/... ./util/...

      - name: Build backend
        run: go build ./...
